apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: team-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
   - host: nginx-arm.devsecops.wisesight.dev
     http:
      - paths:
         - path: /
           pathType: Prefix
           backend:
            service:
             name: nginx
             port:
              number: 80