apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue-app-ingress
  namespace: team-uncle
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: uncle-arm.devsecops.wisesight.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue-app-service
                port:
                  number: 80
