apiVersion: v1
kind: Service
metadata:
  name: { { .Values.serviceName } }
spec:
  selector:
    app: { { .Values.serviceName } }
  ports:
    - port: { { .Values.port } }
      targetPort: { { .Values.port } }
