---
# Source: vue-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vue-app
spec:
  selector:
    app: vue-app
  port:
   - protocol: TCP
     port: 8080
     targetPort: 8080
  type: LoadBalancer
---
# Source: vue-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  namespace: default
  labels:
    app: vue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app
        image: usesir/vue-app:beta
        ports:
        - containerPort: 8080
