deployment:
  name: "vue-app-deployment"
  namespace: "default"
  replicas: 2
  image: "usesir/vue-app:x86"
  port: 80

service:
  name: "vue-app-service"
  port: 8080
  protocol: TCP
  type: ClusterIP
